### ISSUE TITLE
场景咨询

### ISSUE THREAD

**Issue by suzaichuan** [metartc/metaRTC#1]
hi，
    没看明白具体场景。是不是就是一个终端？必须运行在有声卡gpu的设备上。
    能否作网关？
    用浏览器访问是否直接可以使用？
    谢谢！

**Comment by daxiondi** [comment]
> hi， 没看明白具体场景。是不是就是一个终端？必须运行在有声卡gpu的设备上。 能否作网关？ 用浏览器访问是否直接可以使用？ 谢谢！
浏览器使用正在开发中，你的需求是什么呢？

**Comment by suzaichuan** [comment]
hi,
      非常感谢 热心回答。
      只是想了解具体使用场景，比如janus 是网关，srs 是服务器等。这个产品位置是哪里呢？
      
BR

**Comment by suzaichuan** [comment]
hi
   能否用作网关GW实现这种需求：
                 rtmp            rtp
         srs <---->【GW】<--->voip server
         或者
                 rtmp            rtc
         srs <---->【GW】<--->voip server
或者
                 rtc                    rtc
         srs <---->【GW】<--->voip server        
        双向呼叫。

BR
