### ISSUE TITLE
请问压缩包里能否提供windows第三方库的dll和lib

### ISSUE THREAD

**Issue by apzy** [metartc/metaRTC#10]
目前windows压缩包里bin目录只提供了库的debug的dll，希望能提供下已经编译好的windows库的，一个完整的bin目录。感谢！

**Comment by yangrtc** [comment]
release的都有
https://github.com/metartc/metaRTC/releases/tag/4.0.023

**Comment by apzy** [comment]
看到了，因为是在thirdparty目录下，所以没有发现
