### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Hoke** [metartc/metaRTC#15]
\Users\L\AppData\Local\Temp\metapushstream5.exe.5576.10250.jom
speexdsp.lib(resample.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
fatal error C1900: “P1”(第“20210202”版)和“P2”(第“20180423”版)之间 Il 不匹配

**Comment by faststone** [comment]
这个问题我也遇到过，编译metapushstream5的时候，使用的是QT5.14版本，查询这个错误可能是库版本不一致导致的。然后安装了vs2019和Qt6。在QT6中编译器选择MSVC2019 64Bit，然后就没有错误了。

**Comment by yangjiechina** [comment]
> \Users\L\AppData\Local\Temp\metapushstream5.exe.5576.10250.jom speexdsp.lib(resample.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能 fatal error C1900: “P1”(第“20210202”版)和“P2”(第“20180423”版)之间 Il 不匹配
重新编译speexdsp:
1.https://github.com/xiph/speexdsp/archive/refs/tags/SpeexDSP-1.2.1.zip
2.用里面的VS2008编译，自己新建一个x64 debug调试器
3.注意编译后的lib路径和打印的不一致：实际在主目录的lib文件夹下.
4.替换thirdparty下面的speexdsp.lib
