### ISSUE TITLE
Android 编译问题

### ISSUE THREAD

**Issue by leo94666** [metartc/metaRTC#17]
![e700a448edc76b461e3d2424aef1b9f](https://user-images.githubusercontent.com/71742460/183031492-162722c8-9bd2-4dcd-8bb1-fc7af54fb436.png)

android遇到这样的问题，ndk 为 r18b，API为28

**Comment by yangrtc** [comment]
安卓版本建议用6.0最新版
Android metaRTC6.0 编译指南
https://blog.csdn.net/m0_56595685/article/details/128504114
