### ISSUE TITLE
metaRtc 5.0windows 下这个库链接错误

### ISSUE THREAD

**Issue by HammerZhao** [metartc/metaRTC#19]
下载的 https://github.com/metartc/metaRTC/releases/tag/v5.0-b5 下的
[metartc5_b5.win.7z](https://github.com/metartc/metaRTC/releases/download/v5.0-b5/metartc5_b5.win.7z)  编译

使用qt 4.3.1 配置vs2019 发现链接 speexdsp.lib 出现问题

link /NOLOGO /DYNAMICBASE /NXCOMPAT /ignore:4099 /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\bin\app_win_debug\metap2p5.exe @C:\Users\Hao\AppData\Local\Temp\metap2p5.exe.5780.2016.jom
speexdsp.lib(mdf.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
fatal error C1007: 无法识别的标志“-Ot”(在“p2”中)

**Comment by yangrtc** [comment]
如果你的编译器链接不了，可以用自己的编译器重新编译一个，源码在metartc5.thirdparty.src.7z文件中

**Comment by HammerZhao** [comment]
感谢已经解决
