### ISSUE TITLE
 Android 编译问题

### ISSUE THREAD

**Issue by chenzhu005774** [metartc/metaRTC#20]
在编译 libmetartc 和libmetartccore 抱错， 能否出一个分支，直接 使用源码，便于修改和减少编译问题

**Comment by yangrtc** [comment]
Android metaRTC6.0 编译指南
https://blog.csdn.net/m0_56595685/article/details/128504114

**Comment by blueskiner** [comment]
截止2023.01.09的节点对应的Android版本，使用android platform为29。可以使用android-ndk-r21e和r22b进行上述2个模块的编译，也可以降低gradle版本进行编译，我是直接使用最新的gradle编译的。
