### ISSUE TITLE
srs 5.0 推流奔溃

### ISSUE THREAD

**Issue by iarray** [metartc/metaRTC#25]
请求
POST /rtc/v1/publish/ HTTP/1.1
Host: xxxxxxxxx:1985
Accept: */*
Content-Type:application/json;charset=UTF-8
Content-Length: 1809

{"api":"http://xxxxxxxxx/rtc/v1/publish/","streamurl":"webrtc://xxxxxxxxx","clientip":null,"sdp":"v=0\r\no=MetaRtc 139996530989024 2 IN IP4 0.0.0.0\r\ns=MetaRtcSession\r\nt=0 0\r\na=ice-lite\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS live/abc\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:le18\r\na=ice-pwd:0zr1vr92461614605c6763hn652193q9\r\na=fingerprint:sha-256 10:E0:37:81:BD:D3:F4:92:B2:4B:3F:C8:0F:60:49:70:1E:60:0F:8E:37:29:34:4F:EB:9F:F3:12:74:A4:B4:CB\r\na=setup:actpass\r\na=mid:0\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=sendonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ssrc:192989707 cname:8hb4p4296d5o8143\r\na=ssrc:192989707 msid:- y0hkj870-o917-87nr-5e14-8ndkht8502e8\r\na=ssrc:192989707 mslabel:-\r\na=ssrc:192989707 label:y0hkj870-o917-87nr-5e14-8ndkht8502e8\r\nm=video 9 UDP/TLS/RTP/SAVPF 125 114\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:le18\r\na=ice-pwd:0zr1vr92461614605c6763hn652193q9\r\na=fingerprint:sha-256 10:E0:37:81:BD:D3:F4:92:B2:4B:3F:C8:0F:60:49:70:1E:60:0F:8E:37:29:34:4F:EB:9F:F3:12:74:A4:B4:CB\r\na=setup:actpass\r\na=mid:1\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=sendonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:114 red/90000\r\na=ssrc:192989708 cname:8hb4p4296d5o8143\r\na=ssrc:192989708 msid:- 3592y622-mu54-1216-62k0-qe5nn38766m5\r\na=ssrc:192989708 mslabel:-\r\na=ssrc:192989708 label:3592y622-mu54-1216-62k0-qe5nn38766m5\r\n"}
resp = HTTP/1.1 200 OK
Connection: Close
Content-Length: 1522
Content-Type: application/json
Server: SRS/5.0.19(Leo)

**srs响应成功的**
"code":0,"server":"vid-z8zr66z","sdp":"v=0
o=SRS/5.0.19(Leo) 34361231696 2 IN IP4 0.0.0.0
s=SRSPublishSession
t=0 0
a=ice-lite
a=group:BUNDLE 0 1
a=msid-semantic: WMS live/abc
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=ice-ufrag:9b90541m
a=ice-pwd:0z4a04fr702r3w06d572vg9734679a15
a=fingerprint:sha-256 AD:9D:B3:76:30:E4:5B:4B:23:97:85:65:FC:B6:00:1E:F1:54:DA:32:0C:AC:DE:2F:1A:C8:24:02:93:E4:56:96
a=setup:passive
a=mid:0
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=candidate:0 1 udp 2130706431 xxxxxxxxx 8000 typ host generation 0
m=video 9 UDP/TLS/RTP/SAVPF 125 114
c=IN IP4 0.0.0.0
a=ice-ufrag:9b90541m
a=ice-pwd:0z4a04fr702r3w06d572vg9734679a15
a=fingerprint:sha-256 AD:9D:B3:76:30:E4:5B:4B:23:97:85:65:FC:B6:00:1E:F1:54:DA:32:0C:AC:DE:2F:1A:C8:24:02:93:E4:56:96
a=setup:passive
a=mid:1
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:114 red/90000
a=candidate:0 1 udp 2130706431 xxxxxxxxx 8000 typ host generation 0
","sessionid":"9b90541m:le18"
startRtc,port=11262
candidate:ip==xxxxxxxxx,type=host,port=8000
candidate:ip==xxxxxxxxx,type=host,port=8000
remoteIp=xxxxxxxxx,port=8000
 dtls is mbedtls
 udp server is starting,localPort=11262[11:05:38] Yang ERROR: send stun fail!

[11:05:39] Yang ERROR: send stun fail!
[11:05:40] Yang ERROR: send stun fail!
[11:05:40] Yang ERROR: send stun fail!
[11:05:41] Yang ERROR: send stun fail!

**Comment by iarray** [comment]
找到原因了, 还是因为使用域名引起的. 域名被解析成IP  255.255.255.255 了

**Comment by wealook** [comment]
> 找到原因了, 还是因为使用域名引起的. 域名被解析成IP 255.255.255.255 了

请问直接传域名，最终可以成功吗

**Comment by iarray** [comment]
> > 找到原因了, 还是因为使用域名引起的. 域名被解析成IP 255.255.255.255 了
> 
> 请问直接传域名，最终可以成功吗

我修改了源码才可以 , 不然srs会返回400错误

**Comment by wealook** [comment]
> > > 找到原因了, 还是因为使用域名引起的. 域名被解析成IP 255.255.255.255 了
> > 
> > 
> > 请问直接传域名，最终可以成功吗
> 
> 我修改了源码才可以 , 不然srs会返回400错误
方便说一下大致需要改哪吗，我这边也在尝试改源码，发现传域名 yang_http_post 发起请求都是失败的

**Comment by iarray** [comment]
YangSrsConnection.c

```
int32_t yang_srs_getSignal(YangRtcSession* session,SrsSdpResponseType* srs,char* sdp) {
	int32_t err = Yang_Ok;
	char *srsSdp = (char*)calloc(1,1024*12);
	char qt = '"';
	YangStreamOptType role=session->context.streamConfig->streamOptType;
	const char* roleStr=role==Yang_Stream_Play?"play":"publish";

    // 这里用 ip 会返回400 , 要修改成域名 
    //sprintf(srsSdp,
    //        "{\"api\":\"http://%s:%d/rtc/v1/%s/\",\"streamurl\":\"webrtc://%s:%d/%s/%s\",\"clientip\":null,\"sdp\":\"%s\"}",
    //        session->context.streamConfig->remoteIp, session->context.streamConfig->remotePort, roleStr,
    //        session->context.streamConfig->remoteIp, session->context.streamConfig->remotePort, session->context.streamConfig->app, session->context.streamConfig->stream,
    //        sdp);

    sprintf(srsSdp,
            "{\"api\":\"http://%s:%d/rtc/v1/%s/\",\"streamurl\":\"webrtc://%s/%s/%s\",\"clientip\":null,\"sdp\":\"%s\"}",
           session->context.streamConfig->remoteDomain, session->context.streamConfig->remotePort, roleStr,
           session->context.streamConfig->remoteDomain, session->context.streamConfig->app, session->context.streamConfig->stream,
            sdp);

    printf("srsSdp = %s\r\n", srsSdp);


	char apiurl[256] ;
	memset(apiurl,0,sizeof(apiurl));

	sprintf(apiurl, "rtc/v1/%s/", roleStr);
    err=yang_sdp_querySrs(session,srs,role==Yang_Stream_Play?1:0,(char*)session->context.streamConfig->remoteIp,session->context.streamConfig->remotePort,apiurl, srsSdp);

	yang_free(srsSdp);


	return err;
}
```

**Comment by iarray** [comment]
> > > > 找到原因了, 还是因为使用域名引起的. 域名被解析成IP 255.255.255.255 了
> > > 
> > > 
> > > 请问直接传域名，最终可以成功吗
> > 
> > 
> > 我修改了源码才可以 , 不然srs会返回400错误
> > 方便说一下大致需要改哪吗，我这边也在尝试改源码，发现传域名 yang_http_post 发起请求都是失败的

还有一处YangRtcConnection.c
int32_t yang_rtcconn_startRtc(YangRtcSession* session,char* sdp){

	yang_trace("\nstartRtc,port=%d",session->context.streamConfig->localPort);

	session->isServer=session->context.streamConfig->isServer;

	yang_rtcconn_getRemoteSdp(session,sdp);

	session->ice.session.stun.createRequestStunPacket(session,session->remoteIcePwd);


	if(session->context.avinfo->sys.mediaServer==Yang_Server_P2p){
		if(session->context.avinfo->rtc.iceUsingLocalIp==0 &&
				session->ice.iceHandle(&session->ice.session,session,yang_rtcconn_turn_receive,
						session->context.streamConfig->remoteIp,session->context.streamConfig->remotePort)==YangIceTurn){
			yang_create_rtcudp(session->context.udp,session->context.streamConfig->localPort);
			session->context.udp->sendData=yang_rtcconn_turn_sendData;
			yang_rtcconn_startudp(session);
			g_yang_startStunTimer(session->context.udp->session.user);
			return Yang_Ok;
		}
	}

	yang_create_rtcudp(session->context.udp,session->context.streamConfig->localPort);
    //这里域名要解析为ip, 否则updateRemoteAddress内部会把域名转成了 255.255.255.255
    yang_getIp( session->context.streamConfig->remoteDomain, session->context.streamConfig->remoteIp);
    session->context.udp->updateRemoteAddress(&session->context.udp->session,
                                              session->context.streamConfig->remoteIp,  //这里要传ip, 传域名会变255.255.255.255
                                              session->isServer?0:session->context.streamConfig->remotePort);
	yang_rtcconn_startudp(session);
	session->context.udp->start(&session->context.udp->session);
	return Yang_Ok;
}
