### ISSUE TITLE
webrtc推流demo推流失败

### ISSUE THREAD

**Issue by wangdemon** [metartc/metaRTC#30]
(1)不知道什么原因，webrtc推流失败，如下图所示：
![1](https://user-images.githubusercontent.com/20681339/211710684-155b6305-8053-4a43-9261-3b7a53fbad47.png)
是不是webrtc推流，需要服务器？

(2) 从推流ip来看，默认是以webrtc为前缀，如下图所示：
![2](https://user-images.githubusercontent.com/20681339/211710826-b5c4d637-5080-4c0a-8117-71b382a8380d.png)
webrtc前缀的ip，能改为http或者https吗？

(3) 推流界面
推流默认是摄像头，也可以更改为桌面，请问大佬，可以将推流窗口改为某个应用程序界面吗？

(4) 推流音频
推流好像默认选择音频，请问大佬，在推流过程中，可以选择去掉音频吗

**Comment by yangrtc** [comment]
这个是推流推向srs或者zlm的demo

**Comment by wangdemon** [comment]
> 这个是推流推向srs或者zlm的demo

可以推流给srs了

但是，使用metaplayer6播放，一闪而过，

使用vlc播放将metartc的webrtc流转为rtmp流，却没有问题

看下面视频
[https://www.youtube.com/watch?v=qJhlP7jBb-g](视频)

**Comment by wangdemon** [comment]
> > 这个是推流推向srs或者zlm的demo
> 
> 可以推流给srs了
> 
> 但是，使用metaplayer6播放，一闪而过，
> 
> 使用vlc播放将metartc的webrtc流转为rtmp流，却没有问题
> 
> 看下面视频 [视频](https://www.youtube.com/watch?v=qJhlP7jBb-g)

我刚才调试了一下，是因为音频没有插入麦克导致

![2](https://user-images.githubusercontent.com/20681339/212029789-fff31829-b22c-4493-8d0a-7262d8b924b8.png)

**Comment by wangdemon** [comment]
插入麦克风后，metaplay6可以在正常播放了，如下图：
![3](https://user-images.githubusercontent.com/20681339/212031452-829ad7c1-2cee-41ff-9b7a-73803a39834f.png)

但是，metap2p6_html文件夹下的p2pdemo_zb.html，不能播放，看下图
![4](https://user-images.githubusercontent.com/20681339/212031643-3d561ebd-0e7d-44a0-b853-8a1b62c5a080.PNG)

**Comment by yangrtc** [comment]
p2pdemo_zb.html是和metap2p6进行webrtc通信的demo

**Comment by wangdemon** [comment]
> p2pdemo_zb.html是和metap2p6进行webrtc通信的demo

那有没有直接播放metartc流的html的demo？

**Comment by wangdemon** [comment]
> > p2pdemo_zb.html是和metap2p6进行webrtc通信的demo
> 
> 那有没有直接播放metartc流的html的demo？

感谢大佬。随便在网上找个播放webrtc的，就能播放metartc流。

感谢大佬的无私奉献。

大佬做了很多工作。
