### ISSUE TITLE
有没有调用API推流拉流的例程

### ISSUE THREAD

**Issue by xiaogao22** [metartc/metaRTC#36]
目前的demo针对本地摄像头和桌面采集，我这边的场景是拉网络摄像头，然后再做图像分析，再打包推到浏览器端显示，有没有直接调用api推流拉流的例程，数据源可以灵活点，谢谢

**Comment by jetamie** [comment]
同求

**Comment by xiaogao22** [comment]
>我看见他的系统集成到ffmpeg了，这样可以利用ffmpeg做，就是不知道p2p是不是也支持了
