### ISSUE TITLE
web视频无法播放

### ISSUE THREAD

**Issue by lilei-John** [metartc/metaRTC#39]
![图片](https://user-images.githubusercontent.com/21105903/221518817-95763ed8-225a-40c3-887e-d960aca23c4a.png)
![图片](https://user-images.githubusercontent.com/21105903/221519154-0d2eadbc-8833-4e4d-b40d-1ffab868459a.png)
iceCandidateType=0
视频流不通
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=ssrc:160969538 cname:oy84517gxv58tm0r
a=ssrc:160969538 msid:- v9c886ku-9l90-00g8-8g44-736t63425030
a=ssrc:160969538 mslabel:-
a=ssrc:160969538 label:v9c886ku-9l90-00g8-8g44-736t63425030
a=candidate:0 1 udp 2130706431 192.168.1.104 23842 typ host generation 0
a=candidate:1 1 udp 2130706431 192.168.66.130 23842 typ host generation 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:44r5
a=ice-pwd:o3f667961w495y7iiuxqusm9k2x4n49b
a=ice-options:trickle
a=fingerprint:sha-256 0B:F7:A5:50:F9:D9:B1:9A:48:D4:30:BE:41:EA:9C:5D:34:40:06:9A:C0:12:C6:39:50:FF:D8:7A:E2:C7:D4:56
a=setup:passive
a=mid:2
a=sctp-port:5000
a=candidate:0 1 udp 2130706431 192.168.1.104 23842 typ host generation 0
a=candidate:1 1 udp 2130706431 192.168.66.130 23842 typ host generation 0

p2pdemo_zb.html:60 play url  webrtc://192.168.1.104:1988/live/livestream
srs.sdk.p2p.js:48 datachannel onopen:  undefined
srs.sdk.p2p.js:37 connection state change:  connecting
srs.sdk.p2p.js:42 =======>null
connection state change:  connected

**Comment by yangrtc** [comment]
日志显示rtc连接成功，换一个浏览器或者其他机器浏览器再测试一下

**Comment by lilei-John** [comment]
![图片](https://user-images.githubusercontent.com/21105903/222353418-b1151fd9-899a-44f1-9d03-3bc0b716c9f4.png)

换了qq浏览器，火狐，google都不行，应该不是浏览器问题，iceCandidateType=0是可以局域网通的吗?有什么排查方向可以检查的

**Comment by lilei-John** [comment]
![图片](https://user-images.githubusercontent.com/21105903/222362343-10c9ed57-5269-4eb0-8492-c26146a3f0be.png)
使用qq浏览器，火狐，google也无法播放，使用QT客户端播放也不行。可以指一个排查方向吗

**Comment by yangrtc** [comment]
修改yangutil/yangavtype.h 
#define YangH264PayloadType 125
修改为
#define YangH264PayloadType 106

**Comment by lilei-John** [comment]
datachannel close: 
srs.sdk.p2p.js:85 conf.apiUrl:  http://192.168.1.104:1988/rtc/v1/play/
srs.sdk.p2p.js:98 Generated offer:  {api: 'http://192.168.1.104:1988/rtc/v1/play/', tid: '21c4f9f', streamurl: 'webrtc://192.168.1.104:1988/live/livestream', clientip: null, sdp: 'v=0\r\no=- 8418642807847936339 2 IN IP4 127.0.0.1\r\ns…:2\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n'}
srs.sdk.p2p.js:42 =======>{"candidate":"candidate:2844680865 1 udp 2113937151 a02b2632-6d94-436d-8042-d0709c20c86f.local 59481 typ host generation 0 ufrag C4Sv network-cost 999","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"C4Sv"}
srs.sdk.p2p.js:42 =======>{"candidate":"candidate:2844680865 1 udp 2113937151 a02b2632-6d94-436d-8042-d0709c20c86f.local 59483 typ host generation 0 ufrag C4Sv network-cost 999","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"C4Sv"}
srs.sdk.p2p.js:42 =======>{"candidate":"candidate:2844680865 1 udp 2113937151 a02b2632-6d94-436d-8042-d0709c20c86f.local 59485 typ host generation 0 ufrag C4Sv network-cost 999","sdpMid":"2","sdpMLineIndex":2,"usernameFragment":"C4Sv"}
srs.sdk.p2p.js:109 Got sdp:  v=0
o=MetaRtc 140418672114568 2 IN IP4 0.0.0.0
s=MetaRtcSession
t=0 0
a=ice-lite
a=group:BUNDLE 0 1 2
a=msid-semantic: WMS /
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=ice-ufrag:250s
a=ice-pwd:82u4u20ze621j5lq1hm04506215y656k
a=fingerprint:sha-256 2F:9A:E1:6D:9B:24:BB:34:7E:97:37:F1:2B:AB:E5:76:CB:29:B9:0C:90:71:EA:6D:50:52:F6:69:96:00:C6:99
a=setup:passive
a=mid:0
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:83020120 cname:76888f761f4055qg
a=ssrc:83020120 msid:- 2t6q8770-4s4u-d0uk-692y-4605146g02dw
a=ssrc:83020120 mslabel:-
a=ssrc:83020120 label:2t6q8770-4s4u-d0uk-692y-4605146g02dw
a=candidate:0 1 udp 2130706431 192.168.1.104 23189 typ host generation 0
a=candidate:1 1 udp 2130706431 192.168.66.130 23189 typ host generation 0
m=video 9 UDP/TLS/RTP/SAVPF 106
c=IN IP4 0.0.0.0
a=ice-ufrag:250s
a=ice-pwd:82u4u20ze621j5lq1hm04506215y656k
a=fingerprint:sha-256 2F:9A:E1:6D:9B:24:BB:34:7E:97:37:F1:2B:AB:E5:76:CB:29:B9:0C:90:71:EA:6D:50:52:F6:69:96:00:C6:99
a=setup:passive
a=mid:1
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:106 H264/90000
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=ssrc:83020121 cname:76888f761f4055qg
a=ssrc:83020121 msid:- 59396694-8345-355z-483i-ukx5o324czhr
a=ssrc:83020121 mslabel:-
a=ssrc:83020121 label:59396694-8345-355z-483i-ukx5o324czhr
a=candidate:0 1 udp 2130706431 192.168.1.104 23189 typ host generation 0
a=candidate:1 1 udp 2130706431 192.168.66.130 23189 typ host generation 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:250s
a=ice-pwd:82u4u20ze621j5lq1hm04506215y656k
a=ice-options:trickle
a=fingerprint:sha-256 2F:9A:E1:6D:9B:24:BB:34:7E:97:37:F1:2B:AB:E5:76:CB:29:B9:0C:90:71:EA:6D:50:52:F6:69:96:00:C6:99
a=setup:passive
a=mid:2
a=sctp-port:5000
a=candidate:0 1 udp 2130706431 192.168.1.104 23189 typ host generation 0
a=candidate:1 1 udp 2130706431 192.168.66.130 23189 typ host generation 0

p2pdemo_zb.html:60 play url  webrtc://192.168.1.104:1988/live/livestream
srs.sdk.p2p.js:48 datachannel onopen:  undefined
srs.sdk.p2p.js:37 connection state change:  connecting
srs.sdk.p2p.js:42 =======>null
srs.sdk.p2p.js:37 connection state change:  connected



改成106也不行
srs.sdk.p2p.js:48 datachannel onopen:  undefined
srs.sdk.p2p.js:42 =======>null
这个两个报错是否有影响，只传h264不传音频是否有影响，还请帮忙解答

**Comment by yangrtc** [comment]
你下载最新版本再测试，刚补了个bug

**Comment by lilei-John** [comment]
可以出图了，给力

**Comment by wangdemon** [comment]
> 可以出图了，给力

下载哪个版本可以出图？
