### ISSUE TITLE
最新版本的metap2p6_html中能发送数据不能接收数据

### ISSUE THREAD

**Issue by Hubww** [metartc/metaRTC#42]
系统windows10
浏览器chrome：110.0.5481.100
![e0709fe08c9de7f46c1e951565e4ff9](https://user-images.githubusercontent.com/8380392/224532376-046164f2-9a73-4b29-8dd6-13ab9cbf3a3d.png)
还有没有其他调试的办法，感觉数据收到了但是有问题，没有显示出来，4.0版本也测试过也不行

**Comment by yangrtc** [comment]
能否写出详情？如metap2p6_html目录中哪个文件，和哪个demo通信，版本号是多少等等
