### ISSUE TITLE
为什么不能推流

### ISSUE THREAD

**Issue by finch-yihe** [metartc/metaRTC#49]
使用./metartc6_b2.win/win/demo_bin编译好的bin文件yangpushstream6.exe可以使用电脑自带的摄像头进行推流，而使用./metartc6_b2.win/win/metartc6/demo/metapushstream6的代码编译出来的demo程序，无法推流，卡在建立连接上，请问怎么解决？

**Comment by ChinaRush** [comment]
您好，请问解决了吗
