### ISSUE TITLE
p2pdemo_zb.html不能打开metartc视频流

### ISSUE THREAD

**Issue by wangdemon** [metartc/metaRTC#57]
![1](https://github.com/metartc/metaRTC/assets/20681339/9b34d0e1-91ad-497d-bafa-e1bee9277835)

p2pdemo_zb.html 文件无法开metartc流

给的播放demo可以打开metartc流

看下面演示视频

https://github.com/metartc/metaRTC/assets/20681339/d65b8d17-98ca-4001-b9ea-c4ed4e2b14d3

**Comment by yangrtc** [comment]
p2pdemo_zb.html 是播放metap2p6的demo，无法播放srs/zlm等sfu流

**Comment by wangdemon** [comment]
> p2pdemo_zb.html 是播放metap2p6的demo，无法播放srs/zlm等sfu流

那如何用浏览器播放metartc流？
