### ISSUE TITLE
很模糊

### ISSUE THREAD

**Issue by wangdemon** [metartc/metaRTC#58]
使用pushstream例子推流后，很模糊，特别是动态画面，非常的模糊。

下面是静态图片，metartc播放画面和webrtc播放画面对比

0 原始画面
![0](https://github.com/metartc/metaRTC/assets/20681339/b3a036af-1872-4070-8fd3-0335a45ead5e)

1 使用player例子播放metartc流画面
![1](https://github.com/metartc/metaRTC/assets/20681339/1ea2f13b-aaec-4580-bfe9-cf631328c439)

2 使用浏览器播放metartc流画面
![2](https://github.com/metartc/metaRTC/assets/20681339/c7231efc-def0-46d5-ae5c-d9f7df276e52)

3 将浏览器全屏，播放metartc流画面
![3](https://github.com/metartc/metaRTC/assets/20681339/de23c745-f26a-4466-a5b0-e77556c86be2)

4 使用浏览器播放webrtc流画面
![4](https://github.com/metartc/metaRTC/assets/20681339/a35c943c-0dee-41b6-8abf-e962542cd2ba)

5 将浏览器全屏，播放webrtc流画面
![5](https://github.com/metartc/metaRTC/assets/20681339/1efdf114-ccc2-46fd-9b95-014344888919)

**问题：**
## 2 pushstream例子bug较多，目前已发现的bug:
(1) 如果电脑没有接入麦克风，pushstream启动直接崩溃
(2) 如果电脑没有接入扬声器，pushstream启动直接崩溃
(3)将视频编码h264改为h265，程序直接崩溃
(4)将服务器改为zlm，推流没有效果
(5)pushstream推流，自带的推流画面，颜色会变淡
(6)pushstream选择摄像头，摄像头画面会卡顿
(7)选择gpu编码，不管是英伟达，还是英特尔，也是崩溃
(8)yang_config.ini文件中，video的width和height，不设置成640x480，摄像头不显示，width和height不设置成1920x1080,桌面推流不显示

## 3 player例子，也有一些bug
(1) 如果电脑没有接入麦克风，pushstream启动直接崩溃
(2) 如果电脑没有接入扬声器，pushstream启动直接崩溃
(3)打开metartc流，很慢，但是使用网页打开，就非常快

上述测试例子，基于metartc5

**Comment by wangdemon** [comment]
直接上述图片，可能效果不是很明显

可以下载下面图片的压缩包，压缩是上面5张图片的原图

[图片.zip](https://github.com/metartc/metaRTC/files/12837247/default.zip)

**Comment by wangdemon** [comment]
看一下视频对比效果

原始视频
https://github.com/metartc/metaRTC/assets/20681339/f30bd74f-1876-4669-aa15-74e0d7712cfa

metartc
https://github.com/metartc/metaRTC/assets/20681339/2039499d-c195-4d48-8f5c-96b525f082ae

**Comment by yangrtc** [comment]
5.0已经停止更新和技术支持，建议用7.0或者6.0版本
metapushstream只是个音视频推流简易demo，要求必须有摄像头和麦克风
推流h264编码画面质量可以调整openh264编码参数，默认参数牺牲画面质量提升实时性
h265编码依赖265编码libx265.dll，需要将其放入到lib文件夹中

**Comment by wangdemon** [comment]
我还没有深入看代码，通过改YangOpenH264Encoder.cpp文件中openh264参数，确实可以调高画面质量，但是还有如下问题：

- 1 使用player播放metartc，初次显示画面时间要比网页播放慢很多，网页播放metartc，基本上是瞬时的
- 2 网页播放metartc流，在局域网下，会出现间接性卡顿
- 3 多次使用pushstream后，进行推流、停止推流操作，会让推流失败，或者player无法播放流，需要重启srs，个人感觉，srs鲁棒性不好
- 4 我一直尝试pushstream推流给zlm，但是不知道为什么，没有成功，zlm没有提示，pushstream也没有提示

感谢楼主无私奉献，能把国产webrtc做到这么好。
