### ISSUE TITLE
摄像机咨询

### ISSUE THREAD

**Issue by ypy31393936** [metartc/metaRTC#6]
目前拉取的是3.0版本的代码进行测试，用的机器是笔记本，我想问下如何配置可以切换推流的摄像机呢。我改了配置文件的sys.cameraIndexs，但貌似没有用，能否告知下需要修改哪里。

还有一个问题，是否能够只推音频呢，可以的话需要做那些修改。

感谢作者开源这么棒的框架。

**Comment by yangrtc** [comment]
[video]
vIndex=0
修改上面的参数
代码里也可设定
m_context->avinfo.video.vIndex=0/1/2...

**Comment by ypy31393936** [comment]
奇怪 我照着你说的方法试了 但还是不行 不管我是修改配置文件还是代码   貌似都不起作用   只能是默认的笔记本自带的摄像机

**Comment by bianyukun1213** [comment]
您好，请问您找到只推音频的方法了吗？
