### ISSUE TITLE
metaRTC弱网抗丢包的一部分测试

### ISSUE THREAD

**Issue by lion117** [metartc/metaRTC#69]
## 软件版本说明
1. Windows10  LAPTOP- I5-10
2. ubuntu20的虚拟机运行SRS-5
3. metaRTC7 7.0.062
4. clumsy 0.2

## 推拉流说明
1. 推流端本地推流到虚拟机上的SRS服务器
2. 拉流端从虚拟机上的SRS服务器拉流到本地显示

## clumsy 测试结果
1. 1%的丢包率,基本不卡, 不花屏
2. 5%的丢包率, 较为明显的卡顿, 一定程度的花屏
3. 10%的丢包率, 很明显的卡顿和花屏

下面是测试效果
![image](https://github.com/metartc/metaRTC/assets/3996029/00cd6fdf-00e2-41c6-8fd7-75eb95282d35)

## 视频效果
https://github.com/metartc/metaRTC/assets/3996029/995c95c1-a1f1-46c2-97ba-bd75997b8fb1

**Comment by yangrtc** [comment]
这是基于srs的测试，有没有进行p2p测试？

**Comment by yangrtc** [comment]
有没有测试metaRTC和浏览器p2p以及metaRTC to metaRTC p2p呢？
这个测试是测试srs的丢包率情况
