### ISSUE TITLE
4.0.x metap2p4问题

### ISSUE THREAD

**Issue by hujianfeng** [metartc/metaRTC#8]
4.0.x metap2p4_html拉metap2p4流会闪退。

**Comment by yangrtc** [comment]
哪个版本？日志？在yang_log.log文件中

**Comment by hujianfeng** [comment]
版本：4.0.009， 4.0.015。两个版本我都试了一下，现像一样。
日志如下：

driver name uvcvideo card = UVC Camera (046d:0825) cap = 84a00001

{ pixelformat = ''YUYV'', description = ''YUYV 4:2:2'' }
DISCRETE: line-189 0: {640*480}
0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 
{ pixelformat = ''MJPG'', description = ''Motion-JPEG'' }
DISCRETE: line-189 0: {640*480}
0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 
http tcp server is starting,listenPort==1988

**Comment by yangrtc** [comment]
看这个日志，好像没有侦听到任何连接，你下载最新版本再试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 下午2:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metartc/metaRTC] 4.0.x metap2p4问题 (Issue #8)





 
版本：4.0.009， 4.0.015。两个版本我都试了一下，现像一样。
 日志如下：
 
driver name uvcvideo card = UVC Camera (046d:0825) cap = 84a00001
 
{ pixelformat = ''YUYV'', description = ''YUYV 4:2:2'' }
 DISCRETE: line-189 0: {640*480}
 0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 
{ pixelformat = ''MJPG'', description = ''Motion-JPEG'' }
 DISCRETE: line-189 0: {640*480}
 0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 0.frameinterval:1/30
 1.frameinterval:1/25
 2.frameinterval:1/20
 3.frameinterval:1/15
 4.frameinterval:1/10
 5.frameinterval:1/5
 
http tcp server is starting,listenPort==1988

**Comment by hujianfeng** [comment]
用最新的metaRTC-develop和metaRTC-develop/metap2p4_html/p2pdemo_zb.html配合也会。
yang_log.log日志启动后无变化 。qt应用程序输出如下：

09:04:23: Starting /home/hujianfeng/work/srs/metaRTC/metaRTC-develop/bin/app_debug/metap2p4 ...
message=== 0x55eafdac9f00 ..prevideobuffer=== 0x55eafda99d70 ....ret==== 0
YangPlayWidget::PlayOneFrame new data memory. Len=460800 width=640 height=480

09:04:28: 程序异常结束。
09:04:28: The process was ended forcefully.
09:04:28: /home/hujianfeng/work/srs/metaRTC/metaRTC-develop/bin/app_debug/metap2p4 crashed.

**Comment by hujianfeng** [comment]
3.0.b1正常。
